import { Anime } from "src/types/anime";

export const animeDefaultValue: Anime = {
  mal_id: 0,
  url: "",
  images: {
    jpg: {
      image_url: "",
      large_image_url: "",
      small_image_url: "",
    },
    webp: {
      image_url: "",
      large_image_url: "",
      small_image_url: "",
    },
  },
  trailer: {
    youtube_id: "",
    url: "",
    embed_url: "",
  },
  approved: false,
  titles: [],
  title: "",
  title_english: "",
  title_japanese: "",
  title_synonyms: "",
  type: "",
  source: "",
  episodes: 0,
  status: "",
  airing: false,
  aired: {
    from: "",
    to: "",
    prop: {
      from: {
        day: 0,
        month: 0,
        year: 0,
      },
      to: {
        day: 0,
        month: 0,
        year: 0,
      },
      string: "",
    },
  },
  duration: "",
  rating: "",
  score: 0,
  scored_by: 0,
  rank: 0,
  popularity: 0,
  members: 0,
  favorites: 0,
  synopsis: "",
  background: "",
  season: "",
  year: 0,
  broadcast: {
    day: "",
    time: "",
    timeZone: "",
    string: "",
  },
  producers: [],
  licensors: [],
  studios: [],
  genres: [],
  explicit_genres: [],
  themes: [],
  demographics: [],
};
